sudo: required
dist: trusty
language: node_js
node_js:
   - lts/*
cache:
  yarn: true
  directories:
   - $HOME/.npm

branches:
   only:
      - master # will only build for master branch commits
      - /^v\d+\.\d+\.\d+$/

before_install:
  - npm install -g npm@latest
    
install:
  - npm ci

script:
  - npm run build
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/confirm_no_existing_tag.sh; fi'
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./travis/tag.sh "los"; fi'

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: dev
  message: Deploying v$TRAVIS_TAG to Firebase
  skip_cleanup: true
  on:
    tags: true