language: node_js

node_js:
   - lts/*
   

branches:
   only:
      - master # will only build for master branch commits

script:
   - npm run build

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"