sudo: required
dist: trusty
language: node_js
node_js:
   - lts/*
cache:
  yarn: true
  directories:
   - $HOME/.npm

branches:
   only:
      - master # will only build for master branch commits
      - /^v\d+\.\d+\.\d+$/

before_install:
  - npm install -g npm@latest
  - npm install -g eslint
  - npm install -g eslint-plugin-promise
  - npm install -g eslint-plugin-flowtype
  - npm install -g babel-eslint 
    
install:
  - npm ci

script:
  - npm run build
  
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN