language: node_js

node_js:
   - lts/*
   
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    all_branches: true
  script: firebase deploy --token $FIREBASE_TOKEN --non-interactive --only hosting
  project: "los"

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy

script:
   - npm run build
   
notifications:
  email:
    on_failure: change
    on_success: change   