sudo: required
dist: trusty
language: node_js
node_js:
   - lts/*
cache:
  directories:
   - $HOME/.npm

branches:
   only:
      - master # will only build for master branch commits
      - /v\d+\.\d+[a-z]/

before_install:
  - npm install -g npm@latest
    
install:
  - npm ci

script:
  - npm run build
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/confirm_no_existing_tag.sh; fi'
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN