language: node_js

node_js:
   - lts/*
   
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    all_branches: true
  project: "marts"

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy

script:
   - npm run build

after_success:
  - "firebase deploy --token=${FIREBASE_TOKEN}"
   
notifications:
  email:
    on_failure: change
    on_success: change   