language: node_js

node_js:
   - lts/*
   

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - npm install -g --silent firebase-tools && eslint # installs firebase to run firebase deploy
   - npm install -g --silent eslint-plugin-promise 

script:
   - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
