language: node_js

node_js:
   - node

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy

script:
   - npm run build
   
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "los"
  
notifications:
  email:
    on_failure: change
    on_success: change   