language: node_js

node_js:
   - lts/*
   

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - npm install # installs firebase to run firebase deploy

script:
   - npm run build

  deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
