sudo: required
dist: trusty
language: node_js
node_js:
   - lts/*
   
cache:
  directories:
   - $HOME/.npm

branches:
   only:
      - master # will only build for master branch commits
      - /^v\d+\.\d+\.\d+$/

before_install:
  - npm install -g npm@latest
    
install:
  - npm ci


